config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  resources :projects do
    resources :bugs
  end

end

app/models/project.rb
class Project<ApplicationRecord
  validates :title,presence: true
  validates :description, presence: true


  has_many :user_projects
  has_many :users, through: :user_projects
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  has_many :bugs,  dependent: :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:edit,:update,:show,:destroy]
  before_action :authenticate_user!

  def index
    if current_user.usertype == 'manager'
      @project=current_user.created_projects
    elsif current_user.usertype == 'developer'
      @project=current_user.assigned_projects
    elsif current_user.usertype == 'qa'
      @project=current_user.assigned_projects
    end
  end
    
  def new
    @project = Project.new
    unless can? :create, @project
      flash[:alert] = "You are not allowed to create a project"
      redirect_to root_path
    end   
  end
    
  def create
    @project = Project.new(project_params)
    @project.creator_id = current_user.id
    if @project.save
      flash[:success] = "Project was created Successfully"
      redirect_to projects_path
    else
      render 'new', status: :unprocessable_entity
    end
  end
    
  def edit
    unless can? :edit, @project
      flash[:danger] = "You cannot edit other user's project"
      redirect_to user_path(current_user)
    end
  end
    
  def update
    if @project.update(project_params)
      flash[:success] = "Your Project was updated successfully"
      redirect_to projects_path
    else
      render 'edit', status: :unprocessable_entity
      end
  end
    
  def show
    unless can? :show, @project
      flash[:danger] = "You are not allowed to view other user's projects"
      redirect_to projects_path
    end
  end
    
  def destroy
    if can? :destroy, @project
      @project = Project.find(params[:id]).destroy
      flash[:success] = "Project was deleted successfully"
      redirect_to projects_path, status: :see_other
    else
      flash[:danger] = "You cannot delete other user's projects"
    end
  end
    
private
    
  def project_params
    params.require(:project).permit(:title, :description, user_ids: [])
  end
      
  def set_project
    @project = Project.find(params[:id])
  end
    
end

app/views/projects/_form.html.erb
<div class  = "row">
  <div class = "col-md-12">
    <%= form_for(@project, :html => {class: "form-horizontal",role: "form"}) do |f|%>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :title%>
        </div>
        <div class = "col-md-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Enter your title", autofocus: true%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :description%>
        </div>
        <div class = "col-md-10">
          <%=f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter description of the project"%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :Developers %>
        </div>
        <div class = "col-md-8">
          <%=f.select(:user_ids, User.developer.collect{|p|[ p.name, p.id]}, {:prompt=>""}, {:multiple=>true})%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%=f.label :QA%>
        </div>
        <div class = "col-md-8">
          <%=f.select(:user_ids, User.qa.collect {|p|[p.name, p.id]}, {:prompt=>""}, {:multiple=>true})%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "col-md-offset-2 col-md-12">
          <%=f.submit class: "btn btn-primary btn-md btn-xlarge"%>
          <%=link_to "Return to Projects listing", projects_path, class: "btn btn-primary btn-md btn-xlarge"%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/projects/edit.html.erb
<h1 align = "center">Edit the existing Project</h1>

<%= render 'shared/error', obj: @project%>

<%=render 'form'%>

app/views/projects/index.html.erb
<h1 align = "center">All Projects</h1>
<% @project.each do |project|%>
  <br><br>
  <div class = "row">
    <div class = "col-md-12">
      <h4><%=link_to project.title, project_path(project)%></h4>
      <br>
      <p>
        <div class = "float-end"><span class = "quiet"><small>Created <%= time_ago_in_words(project.created_at)%> ago by <%=project.creator.name%></small></span></div>
      </p>
      <p>Description: &emsp; <%= truncate(project.description, length: 70)%></p>
      <%if user_signed_in? && (current_user.usertype == 'manager' && current_user.id == project.creator_id)%>
        <div class="float-end">
          <%=link_to "Edit this Project", edit_project_path(project), class: "btn btn-primary btn-md btn-xlarge" %>
          <%=link_to "Delete this Project", project_path(project), class:"btn btn-primary btn-xs btn-xlarge", 
                                                    data: {"turbo-method": :delete}, method: :delete%>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/projects/new.html.erb
<h1 align = "center">Creating a new Project</h1>


<%= render 'shared/error', obj: @project%>

<%=render 'form'%>

app/views/projects/show.html.erb
<%=render 'shared/page_title', title: "Project Title: #{@project.title.capitalize}"%>
<hr/>
<br>
<h3>Description:</h3>
<p><%= simple_format(@project.description)%></p>
<br>
<p><small>Created By:  <%=@project.creator.name.capitalize%><small></p>
<%if user_signed_in? && (current_user.usertype == 'manager' && current_user.id == @project.creator_id)%>
  <div class="text-end">
    <%=link_to "Edit your Project", edit_project_path, class: "btn btn-primary btn-md btn-xlarge" %>
    <%=link_to "Delete this Project", project_path(@project), class:"btn btn-primary btn-xs btn-xlarge", 
                                             data: {"turbo-method": :delete}, method: :delete%>
  </div>
<%end%>
<%if user_signed_in? && current_user.usertype == 'qa'%>
  <div class="text-center">
    <%=link_to "Create a Bug", new_project_bug_path(@project), class: "btn btn-primary btn-md btn-xlarge"%>
  </div>
<%end%>    
<br>
<div class="text-center">
  <%=link_to "Return to projects listing", projects_path, class: "btn btn-primary btn-md btn-xlarge"%>
</div>
<hr/>
<%if @project.bugs.count != 0 %>
  <h2 align="center">Bugs created by QA: </h2>
  <% @project.bugs.each do |bug|%>
    <br><br>
    <div class = "row">
      <div class = "container">
        <div class = "col-md-12 well">
          <h4><%=link_to bug.title, project_bug_path(@project, bug)%></h4>
          <div class = "float-end">
            <span class = "quiet">
              Created <%= time_ago_in_words(bug.created_at) %> ago by <%=bug.bug_creator.name.capitalize%>
            </span>
          </div>    
        </div>
      </div>
    </div>
  <%end%>
<%else%>
  <h4 align = "center">NO BUGS YET</h4>
<%end%>