config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  resources :projects do
    resources :bugs
  end

end

app/models/bug.rb
class Bug< ApplicationRecord
  validates :title, presence: true, uniqueness: { scope: :project_id }
  validates :bug_status, presence: true
  validates :bug_type, presence: true

  belongs_to :project

  belongs_to :bug_creator, class_name: "User", foreign_key: "creator_id"
  belongs_to :bug_solver, class_name: "User", foreign_key: "solver_id"


  mount_uploader :image, FileUploader

  enum bug_type: 
  {
    feature: 0,
    bug: 1
  }

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:edit,:update,:show,:destroy]
  before_action :authenticate_user!

  def new
    @bug = Bug.new()
    @project = Project.find_by(id: params[:project_id])
    @developers = @project.users.developer
    unless can? :create, @bug
      flash[:alert] = "You cannot create a bug"
      redirect_to user_path(current_user)
    end
  end

  def create
    @bug = Bug.new(bug_params)
    @bug.creator_id = current_user.id
    @project = Project.find_by(id: params[:project_id])
    @bug.project_id = @project.id
    @developers = @project.users.developer
    if @bug.save
      flash[:success] = "Bug was created successfully"
      redirect_to project_path(@project)
    else 
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    unless can? :show, @bug
      flash[:danger] = "You cannot view other QA's created bugs"
      redirect_to user_path(current_user)
    end
  end

  def edit
    if can? :edit, @bug
      @bug = Bug.find(params[:id])
      @project = Project.find_by(id: params[:project_id])
      @developers = @project.users.developer
      @bug.project_id = @project.id
    else
      flash[:danger] = "You cannot edit other QA's bugs"
      redirect_to user_path(current_user)
    end
  end

  def update
    @project = Project.find_by(id: params[:project_id])
    if @bug.update(bug_params)
      flash[:success] = "Bug was updated successfully"
      redirect_to project_bug_path(@bug)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if can? :destroy, @bug
      @bug = Bug.find(params[:id]).destroy
      flash[:success] = "Bug was deleted successfully"
      redirect_to user_path(current_user), status: :see_other
    else
      flash[:danger] = "You cannot delete this bug"
      redirect_to root_path
    end
  end

private

  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :bug_type, :bug_status, :image, :solver_id, :project_id)
  end

  def set_bug
    @bug = Bug.find(params[:id])
  end

end

app/views/bugs/_form.html.erb
<div class = "row">
  <div class = "col-md-12">
    <%= form_for(@bug, :html => {class: "form-horizontal", role: "form"}, url: project_bugs_path) do |f|%>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :title%>
        </div>
        <div class = "col-md-6">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter your title", autofocus: true%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :description%>
        </div>
        <div class="col-md-6">
          <%=f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter description of the bug"%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :deadline%>
        </div>
        <div class = "col-md-2">
          <%=f.date_field :deadline, class: "form-control", placeholder: "Enter deadline"%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :Assign_Developers%>
        </div>
        <div class = "col-md-8">
          <%= f.select(:solver_id, @developers.collect{|p|[ p.name, p.id]}, {:prompt=>""})%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :screenshot%>
        </div>
        <div class = "col-md-4">
          <%=f.file_field :image, class: "form-control"%>
        </div>
      </div>
      <br>
      <div class = "form-group">
        <div class = "col-md-6">
          <%= f.label :BugType %> &emsp;
          <%= f.select :bug_type, ["feature", "bug"] %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-4">
          <%=f.label :status%>&emsp;
        </div>
        <div class = "col-md-4">
          <%= f.select :bug_status, ["New", "Started", "Completed"] %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "col-md-offset-2 col-md-12">
          <%=f.submit class: "btn btn-primary btn-md btn-xlarge"%>
          <%=link_to "Return", project_path(@project), class: "btn btn-primary btn-md btn-xlarge"%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/bugs/edit.html.erb
<%=render 'shared/page_title', title: "Edit Bug"%>
<hr/>
<%=render 'shared/error', obj: @bug%>
<div class = "row">
  <div class = "col-md-12">
    <%= form_for(@bug, :html => {class: "form-horizontal", role: "form"}, url: project_bug_path(@project, @bug)) do |f|%>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :title%>
        </div>
        <div class = "col-md-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Enter your title", autofocus: true%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :description%>
        </div>
        <div class = "col-md-6">
          <%=f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter description of the bug"%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :deadline%>
        </div>
        <div class = "col-md-2">
          <%=f.date_field :deadline, class: "form-control", placeholder: "Enter deadline"%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :Assign_Developers%>
        </div>
        <div class = "col-md-8">
          <%=f.select(:solver_id, @project.users.developer.collect{|p|[ p.name, p.id]}, {:prompt=>""})%>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-8">
          <%=f.label :screenshot%>
        </div>
        <div class = "col-md-4">
          <%=f.file_field :image, class: "form-control"%>
        </div>
      </div>
      <br>
      <div class = "form-group">
        <div class = "col-md-6">
          <%= f.label :BugType %>&emsp;
          <%= f.select :bug_type, ["bug", "feature"] %>
        </div>
      </div> 
      <div class = "form-group">
        <div class = "control-label col-md-4">
          <%=f.label :status%>&emsp;
        </div>
        <div class = "col-md-4">
          <%= f.select :bug_status, ["New", "Started", "Completed"] %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "col-md-offset-2 col-md-12">
          <%=f.submit class: "btn btn-primary btn-md btn-xlarge"%>
          <%=link_to "Return", project_bug_path(@bug), class: "btn btn-primary btn-md btn-xlarge"%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/bugs/new.html.erb
<%=render 'shared/page_title', title: "Create Bug"%>
<%=render 'shared/error', obj: @bug%>
<hr/>
<%=render 'form'%>

app/views/bugs/show.html.erb
<%=render 'shared/page_title', title: "Title: #{@bug.title}"%>
<hr/>
<%if !@bug.description.blank?%>
  <h3>Description:</h3>
  <p><%=simple_format(@bug.description)%></p>
<%end%>
<%if @bug.image.blank? %>
  <h3>NO IMAGE UPLOADED</h3>
<%else%>
  <h3>Bug Image: </h3>
  <p align = "center"><img src= "<%= @bug.image%>"width = "400" height = "400"</p>
<%end%>
<p><strong>Type: </strong><%= @bug.bug_type%></p>
<p><strong>Status: </strong><%= @bug.bug_status%></p>
<%if !@bug.deadline.blank?%>
  <p><strong>Deadline: </strong><%=@bug.deadline%></p>
<%end%>
<p><small>Created By: <%= @bug.bug_creator.name.capitalize%><small></p>
<%if user_signed_in? && (current_user.usertype == 'qa' && current_user.id == @bug.creator_id)%>
  <div class="text-end">
    <%=link_to "Edit this Bug", edit_project_bug_path, class: "btn btn-primary btn-md btn-xlarge" %>
    <%=link_to "Delete this Bug", project_bug_path(@bug), class:"btn btn-primary btn-xs btn-xlarge", 
                                  data: {"turbo-method": :delete}, method: :delete%>
  </div>
<%end%>
<%if user_signed_in? && (current_user.usertype == 'developer' && current_user.id == @bug.solver_id)%>
  <div class="text-end">
    <%=link_to "Edit this Bug", edit_project_bug_path, class: "btn btn-primary btn-md btn-xlarge" %>
  </div>
<%end%>
<br><hr/>
<div class = "text-center">
  <%= link_to "Return", project_path(@bug.project), class: "btn btn-primary btn-md btn-xlarge"%>
</div>