config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  resources :projects do
    resources :bugs
  end

end

app/views/layouts/_footer.html.erb
<div class="flex-wrapper">
<footer class="bg-light text-center text-white footer">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022
  </div>
  <!-- Copyright -->
</footer>
</div>

app/views/layouts/_message.html.erb
<div class = "container">
  <div class = "col-md-10 col-md-offset-4">
    <div class = "row">
      <% flash.each do |name, msg|%>
        <br>
        <div class="alert alert-<%= name %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= msg %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%=link_to "BugTrack",root_path%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" <%=link_to "Home",root_path%> <span class="sr-only">(current)</span></a>
      </li>
      <%if user_signed_in?%>
        <li class="nav-item active">
          <a class="nav-link" <%=link_to "Your Profile",user_path(current_user)%> <span class="sr-only">(current)</span></a>
        </li>
      <%end%>  
      <li class="nav-item active">
        <a class="nav-link" <%=link_to "Projects", projects_path%></a>
      </li>
      <%if user_signed_in? && current_user.usertype=='manager'%>
        <li class="nav-item active">
          <a class="nav-link" <%=link_to "Create new project",new_project_path%></a>
        </li>
      <%end%>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-0 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
    <ul class="navbar-nav col-md-1 mb-1">
      <div>
        <%if user_signed_in?%>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%=current_user.name.capitalize%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" <%=link_to "Edit Your Profile",edit_user_registration_path%></a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" <%=link_to "Logout" ,destroy_user_session_path, data:{"turbo-method": :delete},method: :delete %></a>
            </div>
          </li>
        <%else%>
          <li class="nav-item active">
            <a class="nav-link" <%=link_to "Login", new_user_session_path%></a>
          </li>
        <%end%>
      </div>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bug Tracking System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%=stylesheet_link_tag href="custom", "data-turbo-trak": "reload" %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>
  <%= render 'layouts/navigation' %>
    <div class="container">
      <%=render 'layouts/message'%>
    <body>
      <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
    </body>
</html>